/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pobreAbastece.frontEnd.posto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JLabel();
        jcampoNome = new javax.swing.JTextField();
        jCnpj = new javax.swing.JLabel();
        jcampoCnpj = new javax.swing.JTextField();
        jEnderco = new javax.swing.JLabel();
        jcampoEndereco = new javax.swing.JTextField();
        jprecoEtanol = new javax.swing.JLabel();
        jcampoPrecoEtanol = new javax.swing.JTextField();
        jprecoGasolina = new javax.swing.JLabel();
        jcampoPrecoGasolina = new javax.swing.JTextField();
        jprecoDiesel = new javax.swing.JLabel();
        jcampoPrecoDiesel = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNome.setText("Nome do posto");
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        jcampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 350, 40));

        jCnpj.setText("CNPJ");
        getContentPane().add(jCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, -1));

        jcampoCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoCnpjActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 350, 40));

        jEnderco.setText("Endereço");
        getContentPane().add(jEnderco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, -1));

        jcampoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 40));

        jprecoEtanol.setText("Preço do Etanol");
        getContentPane().add(jprecoEtanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 240, -1));

        jcampoPrecoEtanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoPrecoEtanolActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoPrecoEtanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, 40));

        jprecoGasolina.setText("Preço da Gasolina");
        getContentPane().add(jprecoGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, -1));

        jcampoPrecoGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoPrecoGasolinaActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoPrecoGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 350, 40));

        jprecoDiesel.setText("Preço do Diesel");
        getContentPane().add(jprecoDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 240, -1));

        jcampoPrecoDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoPrecoDieselActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoPrecoDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 350, 40));

        titulo.setFont(new java.awt.Font("Nimbus Sans Becker PBla", 0, 36)); // NOI18N
        titulo.setText("Insira os dados do posto");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 380, 50));

        botaoCadastrar.setText("Cadastrar Posto");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 250, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 250, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pobreAbastece/frontEnd/icons/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoNomeActionPerformed

    private void jcampoCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoCnpjActionPerformed

    private void jcampoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoEnderecoActionPerformed

    private void jcampoPrecoEtanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoPrecoEtanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoPrecoEtanolActionPerformed

    private void jcampoPrecoGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoPrecoGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoPrecoGasolinaActionPerformed

    private void jcampoPrecoDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoPrecoDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoPrecoDieselActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        Posto posto = new Posto();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cadastrar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JLabel jCnpj;
    private javax.swing.JLabel jEnderco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jcampoCnpj;
    private javax.swing.JTextField jcampoEndereco;
    private javax.swing.JTextField jcampoNome;
    private javax.swing.JTextField jcampoPrecoDiesel;
    private javax.swing.JTextField jcampoPrecoEtanol;
    private javax.swing.JTextField jcampoPrecoGasolina;
    private javax.swing.JLabel jprecoDiesel;
    private javax.swing.JLabel jprecoEtanol;
    private javax.swing.JLabel jprecoGasolina;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
