/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pobreAbastece.frontEnd.posto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import pobreAbastece.frontEnd.Principal;

/**
 *
 * @author gabri
 */
public class Posto extends javax.swing.JFrame {

    /**
     * Creates new form Posto
     */
    public Posto() {
        initComponents();
        
        DefaultTableModel tabela = (DefaultTableModel) tabelaPostos.getModel();
        tabelaPostos.setRowSorter(new TableRowSorter(tabela));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPostos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcampoNome = new javax.swing.JTextField();
        jNome = new javax.swing.JLabel();
        jcampoEndereco = new javax.swing.JTextField();
        jEnderco = new javax.swing.JLabel();
        jcampoEtanol = new javax.swing.JTextField();
        jEtanol = new javax.swing.JLabel();
        jcampoDiesel = new javax.swing.JTextField();
        jDiesel = new javax.swing.JLabel();
        jcampoCnpj = new javax.swing.JTextField();
        jCnpj = new javax.swing.JLabel();
        jcampoGasolina = new javax.swing.JTextField();
        jGasolina = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaPostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Local", "Etanol", "Gasolina", "Diesel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPostos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPostosMouseClicked(evt);
            }
        });
        tabelaPostos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaPostosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPostos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 760, 360));

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 240, 50));

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 240, 50));

        jButton5.setText("Cadastrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pobreAbastece/frontEnd/icons/logoPa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pobreAbastece/frontEnd/icons/voltar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 60));

        jcampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 260, 40));

        jNome.setForeground(new java.awt.Color(255, 255, 255));
        jNome.setText("Nome do posto");
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 120, -1));

        jcampoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 640, 40));

        jEnderco.setForeground(new java.awt.Color(255, 255, 255));
        jEnderco.setText("Endereço");
        getContentPane().add(jEnderco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 240, -1));

        jcampoEtanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoEtanolActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoEtanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 110, 40));

        jEtanol.setForeground(new java.awt.Color(255, 255, 255));
        jEtanol.setText("Etanol");
        getContentPane().add(jEtanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 110, -1));

        jcampoDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoDieselActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 110, 40));

        jDiesel.setForeground(new java.awt.Color(255, 255, 255));
        jDiesel.setText("Diesel");
        getContentPane().add(jDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 110, -1));

        jcampoCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoCnpjActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 230, 40));

        jCnpj.setForeground(new java.awt.Color(255, 255, 255));
        jCnpj.setText("CNPJ");
        getContentPane().add(jCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 200, -1));

        jcampoGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcampoGasolinaActionPerformed(evt);
            }
        });
        getContentPane().add(jcampoGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 110, 40));

        jGasolina.setForeground(new java.awt.Color(255, 255, 255));
        jGasolina.setText("Gasolina");
        getContentPane().add(jGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pobreAbastece/frontEnd/icons/fundoPagPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel postos = (DefaultTableModel) tabelaPostos.getModel();
        String[] dados = {jcampoNome.getText(),jcampoEndereco.getText(),jcampoEtanol.getText(),jcampoGasolina.getText(),jcampoDiesel.getText()};
        postos.addRow(dados);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principal tela = new Principal();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoNomeActionPerformed

    private void jcampoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoEnderecoActionPerformed

    private void jcampoEtanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoEtanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoEtanolActionPerformed

    private void jcampoDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoDieselActionPerformed

    private void jcampoCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoCnpjActionPerformed

    private void jcampoGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcampoGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcampoGasolinaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(tabelaPostos.getSelectedRow() != -1){
        
        DefaultTableModel postos = (DefaultTableModel) tabelaPostos.getModel();
        postos.removeRow(tabelaPostos.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um posto para para excluir");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabelaPostos.getSelectedRow() != -1){
            tabelaPostos.setValueAt(jcampoNome.getText(), tabelaPostos.getSelectedRow(), 0);
            tabelaPostos.setValueAt(jcampoEndereco.getText(), tabelaPostos.getSelectedRow(), 1);
            tabelaPostos.setValueAt(jcampoEtanol.getText(), tabelaPostos.getSelectedRow(), 2);
            tabelaPostos.setValueAt(jcampoGasolina.getText(), tabelaPostos.getSelectedRow(), 3);
            tabelaPostos.setValueAt(jcampoDiesel.getText(), tabelaPostos.getSelectedRow(), 4);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaPostosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaPostosKeyReleased
        
    }//GEN-LAST:event_tabelaPostosKeyReleased

    private void tabelaPostosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPostosMouseClicked
        if(tabelaPostos.getSelectedRow() != -1){
            jcampoNome.setText(tabelaPostos.getValueAt(tabelaPostos.getSelectedRow(), 0).toString());
            jcampoEndereco.setText(tabelaPostos.getValueAt(tabelaPostos.getSelectedRow(), 0).toString());
            jcampoEtanol.setText(tabelaPostos.getValueAt(tabelaPostos.getSelectedRow(), 0).toString());
            jcampoGasolina.setText(tabelaPostos.getValueAt(tabelaPostos.getSelectedRow(), 0).toString());
            jcampoDiesel.setText(tabelaPostos.getValueAt(tabelaPostos.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaPostosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Posto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jCnpj;
    private javax.swing.JLabel jDiesel;
    private javax.swing.JLabel jEnderco;
    private javax.swing.JLabel jEtanol;
    private javax.swing.JLabel jGasolina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcampoCnpj;
    private javax.swing.JTextField jcampoDiesel;
    private javax.swing.JTextField jcampoEndereco;
    private javax.swing.JTextField jcampoEtanol;
    private javax.swing.JTextField jcampoGasolina;
    private javax.swing.JTextField jcampoNome;
    private javax.swing.JTable tabelaPostos;
    // End of variables declaration//GEN-END:variables
}
